services:
  - type: web
    name: my-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3-dev build-essential
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: first app.py  # Change this to match your entry file
    envVars:
      - key: PYTHON_VERSION
        value: 3.10  # Change based on your project needs
